### ISSUE TITLE
Server becoming too slow

### ISSUE THREAD

**Issue by nijel** [phpmyadmin/error-reporting-server#43]
With more and more data coming in the server is becoming really slow. I believe it is mostly caused by missing indexes on fields which are often used for lookups.

**Comment by pratiksethia1** [comment]
I have setup a similar server with 100,000 reports and incidents. The server is responding in less than 1 sec. Demo : http://collg.pe.hu/
PS : No extra index are created.

**Comment by pratik** [comment]
The server is responding very well right now(waiting TTFB : 5-6 sec).
Half an hour ago it was taking 2-3 minutes for responding(waiting TTFB : 2-3 mins).
So i suppose the issue was on server side rather than the scripts or queries.
Every page is responding well. Refer to the images below :

![screenshot](https://cloud.githubusercontent.com/assets/6122429/7252362/f1f2619e-e851-11e4-94c6-0df1baea3257.png)

![screenshot](https://cloud.githubusercontent.com/assets/6122429/7252364/f3843b04-e851-11e4-9d70-725edc425ec5.png)

![screenshot](https://cloud.githubusercontent.com/assets/6122429/7252366/f6b55a1a-e851-11e4-80dc-b82c0fd6584a.png)

![screenshot](https://cloud.githubusercontent.com/assets/6122429/7252367/f8463ec6-e851-11e4-8a8e-736612e45643.png)

**Comment by nijel** [comment]
Maybe it has something to do with structure of the data as well - for example how are incidents grouped.

**Comment by pratik** [comment]
Seems like the server response is fluctuating. Right now, sometimes the request loads quickly and sometimes it's stalled.

**Comment by nijel** [comment]
Seems to be much better now, thanks to @smita786
